### ISSUE TITLE
Longer channel names cut off

### ISSUE THREAD

**Issue by futzlarson** [benjifs/bitbar-slack-team-notifications#5]
Would be cool if longer channel names fit. This one had 2 more characters, which funny enough is longer than the elipsis.

![image](https://user-images.githubusercontent.com/1168673/102722961-bc05e380-42d2-11eb-91d9-6573a6a65cd0.png)

So maybe a wider menu or use the smaller font for channel lines?

**Comment by benjifs** [comment]
I'll add a variable at the top so you can customize the length in the next release. You can use it now too if you if you use the [fix-markasread-ui](https://github.com/benjifs/bitbar-slack-team-notifications/tree/fix-markasread-ui) branch.

I'd like to keep that font and size just so that it matches the built in Bitbar commands but you can always customize that too by changing the `size=13` to whatever. That however wont show the rest of the channel name since I'm limiting that size currently to 15 characters.

**Comment by futzlarson** [comment]
You need to push that branch.

**Comment by benjifs** [comment]
It's all on master now

**Comment by futzlarson** [comment]
Here's a question that I've never quite known how to answer. What am I supposed to do about `package.json` conflicts? If you read the comments [here](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5) it seems like this file maybe shouldn't be committed.

```
$ pull
From https://github.com/benjifs/bitbar-slack-team-notifications
 * branch            master     -> FETCH_HEAD
Updating 8a7e140..2d6af01
error: Your local changes to the following files would be overwritten by merge:
	package-lock.json
Please commit your changes or stash them before you merge.
Aborting
```

I actually avoid using `npm` because of how heavy-handed and bloated it feels, this being another good reason for me. Like, what's so bad about using CDN files (in general, not just this project)?

**Comment by benjifs** [comment]
I think it's safe to delete your `package-lock.json`, and pull the latest changes. The only thing that really changed was the version number.

Generally its preferred to keep `package-lock.json` in version control because those represent the latest installed packages in the development version versus `package.json` could have a minimum, maximum, or actual version being used. In a project like this it probably doesn't matter and it could be removed but just to be consistent, its there.

A way around this too is after deleting `package-lock.json` and getting the latest changes, you could run `npm ci` which will use the versions defined in `package-lock.json` instead of figuring out the right dependencies from `package.json` and also not modify `package-lock.json`.

I generally agree and if possible like to keep my dependencies at a minimum. In this case I use Superagent for fetching and as far as I know, can't use a CDN in nodejs. In any other situation, you could probably use a CDN for the majority of dependencies but you'd still need some dependencies for bundling, minifying, or anything else to prepare a final build so in most production environments its unavoidable and its choosing between which is best.

**Comment by futzlarson** [comment]
There were a bunch of changes but I blew 'em away and pulled.

I am sure there are benefits to npm at a certain scale (or team size), but as the only dev, I found the problems outweighed the advantages (which to me were zero). I also am not using node. And I don't bundle or minify anything. Not only are the CDN libraries already minified, but they're a single line of code and no compiling needed. Anyway, that's just my own personal rant.

I'll wait for another notification in the longer channel and see how it goes. I'll reopen if needed.

**Comment by futzlarson** [comment]
Yep, worked great!
