### ISSUE TITLE
DM labels incorrect

### ISSUE THREAD

**Issue by futzlarson** [benjifs/bitbar-slack-team-notifications#7]
Showing up as:

![image](https://user-images.githubusercontent.com/1168673/104748590-e4d99700-571f-11eb-992b-df8958b1ef84.png)

Instead of:

![image](https://user-images.githubusercontent.com/1168673/104748618-ee62ff00-571f-11eb-9136-b151b438f24e.png)

Seems like `mpdm-` could be Multiple Person Direct Message?

**Comment by benjifs** [comment]
That's correct. I wasn't sure what would be a better way to output that for a group since something like `@personOne, @personTwo` could get truncated as `@personOn...` and look like a DM. Do you have any suggestion on how to represent that other than with `#mpdm-`?

**Comment by futzlarson** [comment]
`(Group message)`?

**Comment by benjifs** [comment]
Group message is maybe too long for the space. This is sort of how that would look with `Group`:
![](https://user-images.githubusercontent.com/4167938/104776718-678b4200-5772-11eb-906c-01daedade9c5.png)

**Comment by futzlarson** [comment]
Hmm. What about `2 people: @whoever, @foobar`? Or can the menu just be wider?

**Comment by benjifs** [comment]
`MAX_LENGTH` can be changed and defaults to 18. Not sure if I like this but grouping into `Channels` and `Direct messages` like Slack does sort of helps.

I think I'd rather have a different symbol represent a group so `@` is for DMs, `#` for Channels, and maybe `>` for Groups to keep it cleaner.

These example have `MAX_LENGTH` set to 50
![](https://user-images.githubusercontent.com/4167938/104789764-bb575480-578d-11eb-8950-2c993ca1c6ad.png)

![](https://user-images.githubusercontent.com/4167938/104789776-be524500-578d-11eb-9923-c6de3e39631e.png)


Thoughts?

**Comment by benjifs** [comment]
Actually after looking it over for a bit, the second screenshot looks cleaner and more clear to me. The only issue I see is a case where you get a DM and a Group message that has the same person in it and that name is longer than the `MAX_LENGTH`. For example:
![](https://user-images.githubusercontent.com/4167938/104797824-0d619f80-57b9-11eb-80e5-73a29cd4b0a4.png)

That could be avoided by adding a separate "Group messages" section but that seems odd since even in the Slack UI its doesn't show up like that.

**Comment by benjifs** [comment]
@futzlarson just pushed these changes as I had another fix to push. I'll close this issue for now but let me know if you have any other thoughts on this and I can make more changes later.
